//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/NewInputSystem/kartControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @KartControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @KartControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""kartControls"",
    ""maps"": [
        {
            ""name"": ""KartActionMaps"",
            ""id"": ""d705a6ca-8aa2-40ce-9943-1dcb38fab75f"",
            ""actions"": [
                {
                    ""name"": ""Val_Direction"",
                    ""type"": ""Value"",
                    ""id"": ""bfdd401f-6c4b-4bfa-9611-4cffc71dc06b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn_Forward"",
                    ""type"": ""Value"",
                    ""id"": ""398fad94-4942-45c1-a17c-e53aad7b3f1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn_Backward"",
                    ""type"": ""Value"",
                    ""id"": ""ff5e95d6-f0b4-464a-bdc4-94321adc8110"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Btn_Dir_Left"",
                    ""type"": ""Button"",
                    ""id"": ""6b6ddedd-bfab-4c35-a711-a5e757324e35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Btn_Dir_Right"",
                    ""type"": ""Button"",
                    ""id"": ""106e8887-2802-49fd-a693-480abeca10cc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetPosition"",
                    ""type"": ""Button"",
                    ""id"": ""2cd204aa-9d62-4d41-92ed-bf77bcb99008"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""G29_Fwd"",
                    ""type"": ""Value"",
                    ""id"": ""b22eed5c-1236-483b-b13a-0ad20c99e2ad"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""G29_Back"",
                    ""type"": ""Value"",
                    ""id"": ""63571e24-e4a0-4222-af24-c9b3d0bfcf48"",
                    ""expectedControlType"": ""Double"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""G29"",
                    ""type"": ""Value"",
                    ""id"": ""fc8d9993-fad9-4501-ab3c-6c223c7a6043"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""LorR"",
                    ""id"": ""a5383713-f09f-46ac-b21c-5e6c2dfec4ea"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""a843ec68-9abc-4726-945c-2ca21b97deef"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""13ead7bd-0d1f-4472-98b8-44ed0d567286"",
                    ""path"": ""<XInputController>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""13b9c937-620a-49b4-8bea-b9005cc23e49"",
                    ""path"": ""<DualShockGamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""d068526a-9465-4526-8bb3-c83e93fa8d1a"",
                    ""path"": ""<DualShockGamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""796f1ab9-ef5c-4cdc-ab00-9e688e4a643f"",
                    ""path"": ""<DualShockGamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""7a0e9a9d-e737-4d8a-89dc-33dee39c0714"",
                    ""path"": ""<DualShockGamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Val_Direction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""a6425ed2-d8c9-4854-b5bd-83d91fd9e07b"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b58ddf5-14b6-497c-9585-f5243cb75cf1"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""55e84e3a-dd09-43b9-859b-f52fbdf315fa"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4866a3e-0346-4e42-aa73-5125dd9cb683"",
                    ""path"": ""<DualShockGamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50161af3-5fc1-4967-8617-74775f16a88c"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ee761b4-9f4b-456c-a0d1-fa1d17cfc37a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fc3645e-93f1-4afe-9ae8-22caa7621281"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Forward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7f1bd33-05a1-437f-babc-aff567a09279"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f21bde0-a7b5-4c6c-896d-96ca4c411cbc"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64ac9d89-65a9-45a7-9335-aac3188264d4"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6f9c633f-b4e3-46ee-83ed-71def6562025"",
                    ""path"": ""<DualShockGamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f38b083-00ff-4071-a027-508fd7842a08"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""176e7f81-923b-40db-850b-014d3edce77c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b396f1e1-4c12-4901-bff2-c8704ffd9fc3"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Backward"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c7255db-69a0-4ee4-89e7-4dfffb4eb6d8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2bb03c7f-8086-4d4b-af98-d52d8de4ee7a"",
                    ""path"": ""<XInputController>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6681cffc-c819-4111-8384-f07ab3d13c57"",
                    ""path"": ""<DualShockGamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8bd58891-4770-4349-bdc4-8a1a420c08d6"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e888858-0997-48b9-b318-7cea498ec391"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Left"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62694899-eb59-400a-860e-81fe8fa5f733"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7002d239-2707-4059-bdbd-eb3a077c195c"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4e0bc33-420e-424a-a13d-9987d56d4793"",
                    ""path"": ""<DualShockGamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03907fa2-9bb7-4f59-be37-7b3c7c6552d5"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d94dd55-1bf0-48eb-bf00-40094d1401ca"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Btn_Dir_Right"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b38962d5-a19c-4263-97e4-84363a62b227"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a92ef3a0-d916-4472-8a11-859c99f58fde"",
                    ""path"": ""<DualShockGamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6188ec11-eb07-4bd0-931e-bd69c4fd1163"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf523645-8ceb-4573-ae57-820202e3c4d3"",
                    ""path"": ""<DualShockGamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7c89f09-32e6-47e0-ad7b-c6d3f91f832e"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""682a7c69-f90d-4122-9b8c-0139657a5042"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G29_Fwd"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""addde7bd-a87f-4acc-bfa6-0903595735a6"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G29_Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""840156b6-e049-453a-81d7-94accc5bd3c5"",
                    ""path"": ""<HID::Logitech G29 Driving Force Racing Wheel>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""G29"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // KartActionMaps
        m_KartActionMaps = asset.FindActionMap("KartActionMaps", throwIfNotFound: true);
        m_KartActionMaps_Val_Direction = m_KartActionMaps.FindAction("Val_Direction", throwIfNotFound: true);
        m_KartActionMaps_Btn_Forward = m_KartActionMaps.FindAction("Btn_Forward", throwIfNotFound: true);
        m_KartActionMaps_Btn_Backward = m_KartActionMaps.FindAction("Btn_Backward", throwIfNotFound: true);
        m_KartActionMaps_Btn_Dir_Left = m_KartActionMaps.FindAction("Btn_Dir_Left", throwIfNotFound: true);
        m_KartActionMaps_Btn_Dir_Right = m_KartActionMaps.FindAction("Btn_Dir_Right", throwIfNotFound: true);
        m_KartActionMaps_ResetPosition = m_KartActionMaps.FindAction("ResetPosition", throwIfNotFound: true);
        m_KartActionMaps_G29_Fwd = m_KartActionMaps.FindAction("G29_Fwd", throwIfNotFound: true);
        m_KartActionMaps_G29_Back = m_KartActionMaps.FindAction("G29_Back", throwIfNotFound: true);
        m_KartActionMaps_G29 = m_KartActionMaps.FindAction("G29", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // KartActionMaps
    private readonly InputActionMap m_KartActionMaps;
    private List<IKartActionMapsActions> m_KartActionMapsActionsCallbackInterfaces = new List<IKartActionMapsActions>();
    private readonly InputAction m_KartActionMaps_Val_Direction;
    private readonly InputAction m_KartActionMaps_Btn_Forward;
    private readonly InputAction m_KartActionMaps_Btn_Backward;
    private readonly InputAction m_KartActionMaps_Btn_Dir_Left;
    private readonly InputAction m_KartActionMaps_Btn_Dir_Right;
    private readonly InputAction m_KartActionMaps_ResetPosition;
    private readonly InputAction m_KartActionMaps_G29_Fwd;
    private readonly InputAction m_KartActionMaps_G29_Back;
    private readonly InputAction m_KartActionMaps_G29;
    public struct KartActionMapsActions
    {
        private @KartControls m_Wrapper;
        public KartActionMapsActions(@KartControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Val_Direction => m_Wrapper.m_KartActionMaps_Val_Direction;
        public InputAction @Btn_Forward => m_Wrapper.m_KartActionMaps_Btn_Forward;
        public InputAction @Btn_Backward => m_Wrapper.m_KartActionMaps_Btn_Backward;
        public InputAction @Btn_Dir_Left => m_Wrapper.m_KartActionMaps_Btn_Dir_Left;
        public InputAction @Btn_Dir_Right => m_Wrapper.m_KartActionMaps_Btn_Dir_Right;
        public InputAction @ResetPosition => m_Wrapper.m_KartActionMaps_ResetPosition;
        public InputAction @G29_Fwd => m_Wrapper.m_KartActionMaps_G29_Fwd;
        public InputAction @G29_Back => m_Wrapper.m_KartActionMaps_G29_Back;
        public InputAction @G29 => m_Wrapper.m_KartActionMaps_G29;
        public InputActionMap Get() { return m_Wrapper.m_KartActionMaps; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(KartActionMapsActions set) { return set.Get(); }
        public void AddCallbacks(IKartActionMapsActions instance)
        {
            if (instance == null || m_Wrapper.m_KartActionMapsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_KartActionMapsActionsCallbackInterfaces.Add(instance);
            @Val_Direction.started += instance.OnVal_Direction;
            @Val_Direction.performed += instance.OnVal_Direction;
            @Val_Direction.canceled += instance.OnVal_Direction;
            @Btn_Forward.started += instance.OnBtn_Forward;
            @Btn_Forward.performed += instance.OnBtn_Forward;
            @Btn_Forward.canceled += instance.OnBtn_Forward;
            @Btn_Backward.started += instance.OnBtn_Backward;
            @Btn_Backward.performed += instance.OnBtn_Backward;
            @Btn_Backward.canceled += instance.OnBtn_Backward;
            @Btn_Dir_Left.started += instance.OnBtn_Dir_Left;
            @Btn_Dir_Left.performed += instance.OnBtn_Dir_Left;
            @Btn_Dir_Left.canceled += instance.OnBtn_Dir_Left;
            @Btn_Dir_Right.started += instance.OnBtn_Dir_Right;
            @Btn_Dir_Right.performed += instance.OnBtn_Dir_Right;
            @Btn_Dir_Right.canceled += instance.OnBtn_Dir_Right;
            @ResetPosition.started += instance.OnResetPosition;
            @ResetPosition.performed += instance.OnResetPosition;
            @ResetPosition.canceled += instance.OnResetPosition;
            @G29_Fwd.started += instance.OnG29_Fwd;
            @G29_Fwd.performed += instance.OnG29_Fwd;
            @G29_Fwd.canceled += instance.OnG29_Fwd;
            @G29_Back.started += instance.OnG29_Back;
            @G29_Back.performed += instance.OnG29_Back;
            @G29_Back.canceled += instance.OnG29_Back;
            @G29.started += instance.OnG29;
            @G29.performed += instance.OnG29;
            @G29.canceled += instance.OnG29;
        }

        private void UnregisterCallbacks(IKartActionMapsActions instance)
        {
            @Val_Direction.started -= instance.OnVal_Direction;
            @Val_Direction.performed -= instance.OnVal_Direction;
            @Val_Direction.canceled -= instance.OnVal_Direction;
            @Btn_Forward.started -= instance.OnBtn_Forward;
            @Btn_Forward.performed -= instance.OnBtn_Forward;
            @Btn_Forward.canceled -= instance.OnBtn_Forward;
            @Btn_Backward.started -= instance.OnBtn_Backward;
            @Btn_Backward.performed -= instance.OnBtn_Backward;
            @Btn_Backward.canceled -= instance.OnBtn_Backward;
            @Btn_Dir_Left.started -= instance.OnBtn_Dir_Left;
            @Btn_Dir_Left.performed -= instance.OnBtn_Dir_Left;
            @Btn_Dir_Left.canceled -= instance.OnBtn_Dir_Left;
            @Btn_Dir_Right.started -= instance.OnBtn_Dir_Right;
            @Btn_Dir_Right.performed -= instance.OnBtn_Dir_Right;
            @Btn_Dir_Right.canceled -= instance.OnBtn_Dir_Right;
            @ResetPosition.started -= instance.OnResetPosition;
            @ResetPosition.performed -= instance.OnResetPosition;
            @ResetPosition.canceled -= instance.OnResetPosition;
            @G29_Fwd.started -= instance.OnG29_Fwd;
            @G29_Fwd.performed -= instance.OnG29_Fwd;
            @G29_Fwd.canceled -= instance.OnG29_Fwd;
            @G29_Back.started -= instance.OnG29_Back;
            @G29_Back.performed -= instance.OnG29_Back;
            @G29_Back.canceled -= instance.OnG29_Back;
            @G29.started -= instance.OnG29;
            @G29.performed -= instance.OnG29;
            @G29.canceled -= instance.OnG29;
        }

        public void RemoveCallbacks(IKartActionMapsActions instance)
        {
            if (m_Wrapper.m_KartActionMapsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IKartActionMapsActions instance)
        {
            foreach (var item in m_Wrapper.m_KartActionMapsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_KartActionMapsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public KartActionMapsActions @KartActionMaps => new KartActionMapsActions(this);
    public interface IKartActionMapsActions
    {
        void OnVal_Direction(InputAction.CallbackContext context);
        void OnBtn_Forward(InputAction.CallbackContext context);
        void OnBtn_Backward(InputAction.CallbackContext context);
        void OnBtn_Dir_Left(InputAction.CallbackContext context);
        void OnBtn_Dir_Right(InputAction.CallbackContext context);
        void OnResetPosition(InputAction.CallbackContext context);
        void OnG29_Fwd(InputAction.CallbackContext context);
        void OnG29_Back(InputAction.CallbackContext context);
        void OnG29(InputAction.CallbackContext context);
    }
}
